# Generated by Django 5.1.1 on 2024-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="best_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
