# Generated by Django 5.1.1 on 2024-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0002_product_best_seller_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="best_seller",
        ),
        migrations.AddField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
