# Generated by Django 5.1.1 on 2024-09-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("traders", "0003_remove_product_best_seller_product_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cost",
        ),
    ]
